version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Running pre-build tasks...
  build:
    commands:
      - echo Building the project...
      - python setup.py build
  post_build:
    commands:
      - echo Running post-build tasks...
      - python setup.py test

artifacts:
  files:
    - '**/*'
  discard-paths: yes
